### ISSUE TITLE
Networkmanager for use on the BTP XF OS and a Kivy based frontend

### ISSUE THREAD

**Issue by hjvankatwijk** [hjvankatwijk/btp-public#2]
We need a custom network manager for the BTP XF OS as the current Ubuntu solutions aren't optimized for touchscreens.
The NM needs to control all devices including openvpn.
It should handle wifi passwords in a secure manner.
The frontend must be Kivy based and should work with kivy 2.1 and Python 3.6 and Python 3.8.
Developer should also be available for tec support.

**Comment by yvonne-zz-67** [comment]
I already have such a solution.
Perhaps best to discuss this by email

**Comment by schoolsplay** [comment]
Cool, will do!
